### ISSUE TITLE
JSON field markup issue

### ISSUE THREAD

**Issue by NikolaySav** [64robots/nova-fields#28]
Hello. 
Having an issue with field names of a reasonable length (screenshot). 
This can be fixed by a few markup changes (marked on the right side of the screenshot).
![2018-10-20 23 48 14](https://user-images.githubusercontent.com/13363510/47260355-b29a4a00-d4c2-11e8-8c26-dcf88725a29d.jpg)

Thanks for your packages. Hoping to see this fix soon.

**Comment by NikolaySav** [comment]
Tried to set styles via meta but it didn't work. 
I guess it's because it renders  form-text-field => default field which doesn't baseClasses prop.
![image](https://user-images.githubusercontent.com/13363510/47260842-68699680-d4cb-11e8-9959-2150d9fb82bd.png)

**Comment by disitec** [comment]
Fixed in 0.3.6.

Btw you can use directly `childConfig([])`  instead of withMeta

**Comment by NikolaySav** [comment]
on version 0.3.6 
Still having this issue :/

![image](https://user-images.githubusercontent.com/13363510/47291381-ff3d6c80-d60b-11e8-897c-98684bf0f3ca.png)

And childConfig expects string in docs
![image](https://user-images.githubusercontent.com/13363510/47291313-d3ba8200-d60b-11e8-9822-dfa2c29636f0.png)
