### ISSUE TITLE
How to casts date inside json

### ISSUE THREAD

**Issue by yabasha** [64robots/nova-fields#52]
Hello,

I have created json object as follow:
```
JSON::make('Meta', [
       Boolean::make('Winner')
              ->yesLabel('Yea!')
              ->noLabel('Nope'),
       Date::make('Win Date', 'win_date')
             ->format('DD MMM YYYY'),
       Number::make('Points')
             ->min(0)
             ->max(100)
       ]),
```

When I save the form, `Date field must cast to 'date' in Eloquent model`

I tried to put:
```
protected $casts = [
    'meta' => 'object',
    'win_date' => 'date',
];
```

But it didn't work, please advice,

**Comment by disitec** [comment]
Hey! sorry for the delay. I was in a christmas vacation and I had no time at all.

Can you try this and tell me how it goes?

```php
JSON::make('Meta', [
       Boolean::make('Winner')
              ->yesLabel('Yea!')
              ->noLabel('Nope'),
       Date::make('Win Date', 'win_date')
             ->format('DD MMM YYYY'),
       Number::make('Points')
             ->min(0)
             ->max(100)
       ]),->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
            $value = $request[$requestAttribute];
             // cast your date to a Carbon instance or whatever you need
             dd($value);
             $newValue = "whatever you did";
            // reasign to your model
            $model->{$attribute} = $newValue
        }),
```

Thanks!

**Comment by disitec** [comment]
Feel free to reopen if you still having this issue.

**Comment by Fabcut** [comment]
Sorry to reopen this issue, but I couldn't fix the issue.

I'm using a seperated panel to gather the JSON data for my user.
The fields in this panel are returned by the following method:

`    
protected function dataFields()
    {
        return [
            JSON::make('Data', [

                Date::make('Birthday',"birthday")
                ->format('DD MMM YYYY')
                ->hideFromIndex(),

            ])
        ];
    }
`

How do I apply the  "fillUsing" function here?
Is there any other way to solve the problem except for creating a dedicated column in the table?

Thanks!

**Comment by CBreetzi** [comment]
Thank you very much for this package - it's great!

I'm still having troubles with the date field in JSON columns and the solution you provided above didn't work out.

`    protected function dataFields()
    {
        return [
            JSON::make('Data', [
                Date::make('Birthday',"birthday")
                ->format('DD MMM YYYY')
                ->hideFromIndex(),
            ])
        ];
    }
`

How do I insert the "fillUsing" method here? Are there any other ways of solving this without creating a dedicated column in the database table?

Thanks!

**Comment by tanthammar** [comment]
I have the same problem.
I tried to cast the nested date value on the model to silence Nova errors.
But it did not help.

**Comment by disitec** [comment]
@CBreetzi please can you try this fillUsing and tell me how it goes?

```php
JSON::make('Data', [
                Date::make('Birthday', "birthday")
                ->format('DD MMM YYYY')
                ->hideFromIndex()
            ])
            ->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
                $value = $request[$requestAttribute];
                $value['birthday'] = new \DateTime($value['birthday']);
            }),
```

@tanthammar is this solution also valid for your case?

**Comment by yabasha** [comment]
I did like what you said but I'm still getting `Date field must cast to 'date' in Eloquent model` exception.

Any other ideas,

> Hey! sorry for the delay. I was in a christmas vacation and I had no time at all.
> 
> Can you try this and tell me how it goes?
> 
> ```
> JSON::make('Meta', [
>        Boolean::make('Winner')
>               ->yesLabel('Yea!')
>               ->noLabel('Nope'),
>        Date::make('Win Date', 'win_date')
>              ->format('DD MMM YYYY'),
>        Number::make('Points')
>              ->min(0)
>              ->max(100)
>        ]),->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
>             $value = $request[$requestAttribute];
>              // cast your date to a Carbon instance or whatever you need
>              dd($value);
>              $newValue = "whatever you did";
>             // reasign to your model
>             $model->{$attribute} = $newValue
>         }),
> ```
> 
> Thanks!

**Comment by tanthammar** [comment]
Thank you for your support on this!
Tried your suggestion but it did not work, still getting "..must cast to date error".
But, there is a new error in the log file from the fillUsing(function)

```
local.ERROR: Argument 1 passed to Laravel\Nova\Resource::resolveFields() must be an instance of Laravel\Nova\Http\Requests\NovaRequest, instance of Illuminate\Http\Request given,
```

This is what I tried:
```
protected function rrule()
    {
        return [
                 Date::make('Start', 'dtstart')
                ->withMeta(['value' => $this->rrule['dtstart'] ?? now()->format('Y-m-d h:m:s')])
                ->rules('required')
                ->help('Required. The recurrence start.')
                ->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
                    $value = $request[$requestAttribute];
                    $value['dtstart'] = new \DateTime($value['dtstart']);
                }),
                Date::make('End', 'until')
                ->help('Optional. The limit of the recurrence. Leave empty for unlimited number of events.')
                ->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
                    $value = $request[$requestAttribute];
                    $value['until'] = new \DateTime($value['until']);
                }),
         ];
}
```

**Comment by CBreetzi** [comment]
> @CBreetzi please can you try this fillUsing and tell me how it goes?
> 
> ```
> JSON::make('Data', [
>                 Date::make('Birthday', "birthday")
>                 ->format('DD MMM YYYY')
>                 ->hideFromIndex()
>             ])
>             ->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
>                 $value = $request[$requestAttribute];
>                 $value['birthday'] = new \DateTime($value['birthday']);
>             }),
> ```
> 
> @tanthammar is this solution also valid for your case?

Thank you for assistance @disitec - sorry for the late reply.
I've tried your solution but it didn't work. I'm getting the same error as @tanthammar:

`local.ERROR: Argument 1 passed to Laravel\Nova\Resource::resolveFields() must be an instance of Laravel\Nova\Http\Requests\NovaRequest, instance of Illuminate\Http\Request given,`

**Comment by tanthammar** [comment]
I solved it by creating my own nova date field.

**Comment by disitec** [comment]
Thats great @tanthammar !
There is no R64/Date field at the moment. Would you consider doing a PR for that so anyone having this issue could use your field? That would be awesome.

Thanks!

**Comment by disitec** [comment]
Fixed in 0.7.1

**Comment by nickpoulos** [comment]
I am still seeing this behavior in v0.7.3, however this time using the DateTime field instead of just Date.   I will attempt a fix using same solution as the Date fix.

**Comment by Abdukhaligov** [comment]
JSON::make('Meta', [
       Boolean::make('Winner')
              ->yesLabel('Yea!')
              ->noLabel('Nope'),
       Date::make('Win Date', 'win_date')
              ->resolveUsing(function ($date){
                      return Carbon::parse($date);
               })
             ->format('DD MMM YYYY'),
       Number::make('Points')
             ->min(0)
             ->max(100)
       ]),

**Comment by Abdukhaligov** [comment]
`JSON::make('Meta', [
Boolean::make('Winner')
->yesLabel('Yea!')
->noLabel('Nope'),
Date::make('Win Date', 'win_date')
->resolveUsing(function ($date){
return Carbon::parse($date);
})
->format('DD MMM YYYY'),
Number::make('Points')
->min(0)
->max(100)
]),`

**Comment by Abdukhaligov** [comment]
`        JSON::make('Meta', [
            Boolean::make('Winner')
                ->yesLabel('Yea!')
                ->noLabel('Nope'),
            Date::make('Win Date', 'win_date')
                ->resolveUsing(function ($date){
                  return Carbon::parse($date);
                })
                ->format('DD MMM YYYY'),
            Number::make('Points')
                ->min(0)
                ->max(100)
        ]),`

**Comment by Abdukhaligov** [comment]
JSON::make('Meta', [
            Boolean::make('Winner')
                ->yesLabel('Yea!')
                ->noLabel('Nope'),
            Date::make('Win Date', 'win_date')
                ->resolveUsing(function ($date){
                  return Carbon::parse($date);
                })
                ->format('DD MMM YYYY'),
            Number::make('Points')
                ->min(0)
                ->max(100)
        ]),

**Comment by acidjazz** [comment]
I stumbled upon this with actual nova dates and this worked for me:

```php
                Date::make('Timer end date', 'content->timer_end_date')
                    ->rules('required')
                    ->default(fn() => '2021-12-08')
                    ->resolveUsing(function ($date) {
                        return Carbon::parse($date)->format('Y-m-d');
                    }),
```

**Comment by martin55** [comment]
Hi! I just ran into the similar issue. This is how I solved it using the laravel accessor:

```
public function getContentAttribute(string $value): array
  {
      $value = (array)json_decode($value);
      if (isset($value['timer_end_date']) && $value['timer_end_date']) {
          $value['timer_end_date'] = Carbon::parse($value['timer_end_date']);
      }
      return $value;
  }
```
